### PR TITLE
UI-2961: Support highlight and unhighlight routes with multiple px-map-layer-geojson

### PR DESCRIPTION
**Pull request by mallik-svmx**
- Support highlight and un-highlight routes with `multiple px-map-layer-geojson`.

### CODE REVIEW

**Comment by leslieli** [comment]
@mallik-svmx The changes look ok to me.

But when I tried the demo and found that sometime the segment did not be highlighted well after switched to another route.

The reproduce steps are:
1. click on the first "Short Trip - Overlapped" button, segment (1 ~ 2) is highlighted
2. click on the second "Short Trip - Overlapped" button, segment (3 ~ 4) is highlighted
3. click on the "Short Trip - NotOverlapped" button, segment (4 ~ 5) is highlighted
4. but click on the second "Short Trip - Overlapped" button again, the segment (3 ~ 4) did not be highlighted.

image

**Comment by mallik-svmx** [comment]
@leslieli - You are right. Noticed that the 'updateInst' method doesn't get called only when the exact same previous element instance(layer-geojson)'s segment is clicked. It's bit weird, let me investigate further. Thanks for reviewing!

**Comment by leslieli** [comment]
One option solution might be:
We pass in the selected feature id to the components, in each component, it will look up the related feature data according to the passed-in feature id. If found, then highlighted it, otherwise, unhighlight the whole route. Does it simpler? Just FYI.

**Comment by leslieli** [comment]
@mallik-svmx It failed to update the route even though the data prop was changed. Please check the example in "layer-geojson-close-popup.html".

Seem that it is caused by the changed in your previous PR:
https://github.com/ServiceMax-Engineering/px-map/pull/40/files#diff-1969e4226092591247659dde7dea212cR299

If ```selectedFeature``` is null, it should return ```nextOptions.data``` in ```_toggleHighlightSelectedFeature```

Could you please check this as well? Thanks.

**Comment by mallik-svmx** [comment]
@leslieli I don't quite get /or able to reproduce your last issue by looking at the example in "layer-geojson-close-popup.html". My previous PR /pull/40 takes care of rendering route segment without highlight whenever the selectedFeature is `null` just by returning the unmodified data in '_toggleHighlightSelectedFeature' method in this case, and it doesn't even move forward. Let me know, I will be happy to discuss /understand your issue over skype anytime.

**Comment by leslieli** [comment]
For case # 1, when ```data``` prop is changed and ```selectedFeature``` prop is NULL
It calls below code to update the route in ```updateInst``` method
```
const geoData = this._toggleHighlightSelectedFeature(lastOptions, nextOptions);
this.elementInst.addData(geoData);
```
But when ```selectedFeature``` is NULL, ```_toggleHighlightSelectedFeature``` return the old data  ```lastOptions.data```, not the newly data - ```nextOptions.data```, then the route did not be updated.

For case # 2, it is for when ```data``` prop is changed, but ```selectedFeature``` prop is one feature of old data, which did not exist in newly data, then the ```featureToHighlight``` is not found - undefined, below code will throw exception:
```
JSON.parse(JSON.stringify(featureToHighlight));
```

Let's discuss over Skype if it still is not clear.

**Comment by leslieli** [comment]
@mallik-svmx 
As we discussed over Skype, with current approach/implementation, there would be a problem when switch/highlight segment from different routes, and it will break the data updating.

Maybe we can try the solution mentioned in Jira ticket:
https://servicemax.atlassian.net/browse/UI-2961

**Comment by mallik-svmx** [comment]
- The key thing was to pass-in sleceted feature id /or null(when unhighlighting) did the magic.
- I suppose the layer-geojson component is dynamically generated in DC App without any repeated code.
- The PR takes care of updatedata, NPE error when no matching id and multiple layer-geojson highlight fully functional.

please help reivew. thanks!

**Pull request merged**
