### PR TITLE
MAX-10855: return popup's geocode when open it

### PR DESCRIPTION
**Pull request by leslieli**
We want to center the popup according to it’s geocode.

### CODE REVIEW

**Comment by leslieli** [comment]
@mallik-svmx @sheela-svmx @joshsylvester please help review. Thanks.

**Comment by leslieli** [comment]
@mallik-svmx could you help merge and publish a new build? Thanks.

**Comment by mallik-svmx** [comment]
@leslieli - PR is merged and release tag v3.19.0 is published.

**Comment by leslieli** [comment]
Thanks @mallik-svmx

**Pull request merged**
